default_language_version:
    python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # future migration to ruff/mypy
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   # Ruff version.
  #   rev: v0.11.12
  #   hooks:
  #     # Run the linter.
  #     - id: ruff-check
  #       args: [ --fix ]
  #     # Run the formatter.
  #     - id: ruff-format
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v1.10.0'  # Use the latest stable version
  #   hooks:
  #     - id: mypy
  #       args: [--strict, --ignore-missing-imports] # Add any mypy arguments you need
  #       additional_dependencies: [
  #         # Add any types-* packages or plugins mypy needs
  #         # e.g., types-requests, numpy, pandas, types-pytz, types-python-dateutil
  #         # Based on your dependencies:
  #         "numpy>=1.26.0",
  #         "pandas >=1.3.0",
  #         "types-pytz",
  #         "types-python-dateutil",
  #         "types-requests",
  #         "sqlalchemy[mypy]>=2"
  #       ]
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
        language_version: python3.12
  - repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
